name: Compile and Commit CV PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    name: compile-commit-cv-pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - run: mkdir -p ./output
      - run: typst compile ./cv.typ ./output/CV.pdf --font-path ./src/fonts

      - name: Commit CV PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Compile and Commit PDF
          file_pattern: 'output/CV.pdf'
